envVars:
  TEST_ENV: "test"
credentials:
  - usernamePassword:
      credentialsId: "global.testing.id"
      usernameVariable: "GLOBAL_TEST_USER"
      passwordVariable: "GLOBAL_TEST_PASSWORD"
podTemplates:
  - name: "build"
    config:
      serviceAccount: "helm-client"
      podRetention: "never"
      envVars:
        - envVar:
            key: POD_VAR
            value: "my_value"
      annotations:
        test: mytest
        anothertest: anothertest
      volumes:
        - emptyDirVolume:
            mountPath: "/var/bleh"
        - secretVolume:
            mountPath: "/var/blehbleh"
            secretName: "bitbucket-ssh"
      imagePullSecrets:
        - testdocker
    container:
      name: "mybuild"
      image: "alpine:3.8"
      command: "cat"
      ttyEnabled: true
      resourceRequestCpu: "50m"
      resourceLimitCpu: "100m"
      resourceRequestMemory: "100Mi"
      resourceLimitMemory: "200Mi"
      envVars:
        - envVar:
            key: MY_OWN_ENV_VAR
            value: "my_value"
      ports:
        - portMapping:
            name: "porttest"
            containerPort: 3306
            hostPort: 3306
groups:
  - lock: "bleh"
    podTemplateName: "build"
    stages:
      - name: "build"
        commands:
          - echo "Hello $BLEH"
          - echo "Hello $MY_OWN_ENV_VAR"
          - echo "Hello $POD_VAR"
          - 'echo "user: $TEST_USER, password: $TEST_PASSWORD"'
          - 'echo "global user: $GLOBAL_TEST_USER, global password: $GLOBAL_TEST_PASSWORD"'
        envVars:
          BLEH: "bleh"
        credentials:
          - usernamePassword:
              credentialsId: "testing.id"
              usernameVariable: "TEST_USER"
              passwordVariable: "TEST_PASSWORD"
